#!/usr/bin/env python3
"""Build deterministic grayscale figure derivatives for the v0.14 preprint."""

from __future__ import annotations

import argparse
import hashlib
import io
import json
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "figures/generated"
OUTPUT_DIR = ROOT / "paper/arxiv/figures-bw"
MANIFEST = ROOT / "paper/arxiv/figures-bw-manifest.json"
NAMES = (
    "fig-1-selection-and-stopping.png",
    "fig-2-practical-control-chain.png",
    "fig-3-decision-paths.png",
    "fig-4-trust-evidence-states.png",
    "fig-5-formal-search-and-screening.png",
    "fig-6-evidence-boundaries.png",
    "fig-a1-mutation-response.png",
    "fig-a2-reproducibility-lineage.png",
    "fig-a3-claim-evidence-integrity.png",
    "fig-a4-oko-versioned-correction.png",
)


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare committed derivatives with regenerated bytes")
    args = parser.parse_args()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    records = []
    generated: dict[str, bytes] = {}
    for name in NAMES:
        source = SOURCE_DIR / name
        output = OUTPUT_DIR / name
        with Image.open(source) as image:
            grayscale = image.convert("L")
            buffer = io.BytesIO()
            grayscale.save(buffer, format="PNG", optimize=True, compress_level=9)
            payload = buffer.getvalue()
            width, height = grayscale.size
        generated[name] = payload
        records.append({
            "name": name,
            "source": str(source.relative_to(ROOT)),
            "source_sha256": digest(source),
            "output": str(output.relative_to(ROOT)),
            "output_sha256": hashlib.sha256(payload).hexdigest(),
            "bytes": len(payload),
            "width": width,
            "height": height,
            "mode": "L",
        })
    manifest = {
        "version": "0.14.0",
        "transformation": "Pillow RGB or RGBA to 8-bit grayscale; no crop, rescale, relabel, or data change",
        "figure_count": len(records),
        "figures": records,
        "boundary": "These are presentation derivatives. The released source figures and underlying data remain unchanged.",
    }
    manifest_text = json.dumps(manifest, indent=2) + "\n"
    if args.check:
        failures = [
            name for name, payload in generated.items()
            if not (OUTPUT_DIR / name).is_file() or (OUTPUT_DIR / name).read_bytes() != payload
        ]
        if not MANIFEST.is_file() or MANIFEST.read_text(encoding="utf-8") != manifest_text:
            failures.append("figures-bw-manifest.json")
        if failures:
            raise SystemExit("arXiv monochrome figures differ: " + ", ".join(failures))
        print(f"arXiv monochrome figures: PASS ({len(records)} deterministic derivatives)")
        return 0
    for name, payload in generated.items():
        (OUTPUT_DIR / name).write_bytes(payload)
    MANIFEST.write_text(manifest_text, encoding="utf-8")
    print(f"arXiv monochrome figures: built {len(records)} derivatives")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
